spring.application.name=springdatajpa

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/springdatajpa
spring.datasource.username=root
spring.datasource.password=30jabin30khadka

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:sql.file



